Support for Additional Licenses
daald/dpkg-licenses pull request #3
Opened 2017-02-24 22:49 UTC by gdgib-bina

Thanks to @tsangacw for coding this.  @daald let us know if we can help explain, document or improve this in any way.

2017-02-24 23:55 UTC, daald requested changes
Thx for your input.

I see what you want. But it collides with lib/reader-50-superfuzzy.sh which has similar grep expressions. Obviously, I forgot GPL there. The main difference is that it doesn't yet replace the discovered strings by their keywords. In this aspect, splitting the file is a nice idea for reducing complexity.

I commented lib/reader-60-gpl.sh as an example for what can be improved on the new design. Most importantly, we need to make sure to keep the version number provided and not adding anything as a default (GPL instead of GPL-3)

I see following options:

-  (PREFERRED) remove lib/reader-50-superfuzzy.sh and include its expressions to the new files. These files should then all have the same number in their names because they use the same method. And they should take care of the version number of the license

- keep lib/reader-50-superfuzzy.sh as a single file (don't add the others), add `    -e 'GNU (Lesser )?General Public License'  \` there and change the reporting so that it reports the keywords instead of the descriptive names

- (FAR FAR FUTURE) completely change the architecture in a way that both keyword and descriptive name get reported. this would allow command line options about formatting. probably this should be done in a programming language

2017-02-24 23:55 UTC, daald commented on lib/reader-60-gpl.sh
> +result=$(grep 'GNU General Public License' \
This can heavily be simplified using:

`if grep -qi 'GNU General Public License' "$copyrightfile"; then`

2017-02-24 23:55 UTC, daald commented on lib/reader-60-gpl.sh
> +  echo "GPL-3"
"GNU General Public License" without explicit version should be reported as GPL, not GPL-3

2017-02-24 23:55 UTC, daald commented on dpkg-licenses
> +    license=$(echo $license','$license1)
If several "plugins" report the same string, there is no filtering anymore (`sort -u`)

2017-02-24 23:55 UTC, daald commented on dpkg-licenses
> +    license=$(echo $license','$license1)
and why not just use `license="$license,$license1"`

2017-02-25 01:13 UTC, gdgib-bina commented
Heads up @tsangacw

2020-03-25 22:35 UTC, daald commented
I would be interested in merging this one, but I don't simply want to wipe the formatted output because it is easier readable for terminal users. I just merged a change which introduces csv (and switching the format by command line). I think a third option "--tsv" which enables your format would be nice.

I especially appreciate the additional parsers. I haven't tested them so far, but they look helpful.

And yes: sorry for the very long delay - I guess I just forgot about it..

2020-03-25 23:49 UTC, gdgib-roche commented
No worries, I forgot about it some too.  FWIW, we're happy using our fork right now, and have some intention to switch to a non-bash language for some of this over the long run.

@tsangacw can you take a look through a few of the comments and see if they're worth addressing in the short term?  We should talk offline before you devote too much time.

2021-11-03 18:19 UTC, gdgib-roche commented
We're using an alternative solution now anyway.  Closing this.

2021-11-03 18:19 UTC, closed without merging